using System;
using System.Collections.Generic;

namespace Inventory.Core
{
    /// <summary>
    /// Default in-memory inventory container. Duplicate definitions are allowed (multiset);
    /// instances are tracked by unique incrementing ids generated by this model.
    /// </summary>
    public class InventoryModel : IInventoryModel
    {
        private readonly List<ArtifactInstance> _items = new List<ArtifactInstance>();
        private int _nextInstanceId;

        public IReadOnlyList<ArtifactInstance> Items => _items;

        public event Action<ArtifactInstance> OnItemAdded;
        public event Action<ArtifactInstance> OnItemRemoved;

        public ArtifactInstance Add(string definitionId)
        {
            var instance = CreateDetachedInstance(definitionId);
            _items.Add(instance);
            OnItemAdded?.Invoke(instance);
            return instance;
        }

        public void Return(ArtifactInstance instance)
        {
            if (instance == null)
            {
                throw new ArgumentNullException(nameof(instance));
            }

            if (Contains(instance.InstanceId))
            {
                throw new InvalidOperationException(
                    $"Artifact instance {instance.InstanceId} is already in the inventory.");
            }

            _items.Add(instance);
            OnItemAdded?.Invoke(instance);
        }

        public bool Remove(int instanceId)
        {
            for (int i = 0; i < _items.Count; i++)
            {
                if (_items[i].InstanceId != instanceId)
                {
                    continue;
                }

                var removed = _items[i];
                _items.RemoveAt(i);
                OnItemRemoved?.Invoke(removed);
                return true;
            }

            return false;
        }

        public bool TryGet(int instanceId, out ArtifactInstance instance)
        {
            for (int i = 0; i < _items.Count; i++)
            {
                if (_items[i].InstanceId == instanceId)
                {
                    instance = _items[i];
                    return true;
                }
            }

            instance = null;
            return false;
        }

        public ArtifactInstance CreateDetachedInstance(string definitionId)
        {
            if (string.IsNullOrEmpty(definitionId))
            {
                throw new ArgumentException("Definition id must not be null or empty.", nameof(definitionId));
            }

            return new ArtifactInstance(_nextInstanceId++, definitionId);
        }

        private bool Contains(int instanceId)
        {
            return TryGet(instanceId, out _);
        }
    }
}
